config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'piles#index'

  resources :piles, except: [:show]
  resources :containers, except: [:show]
  resources :graphs, only: [:index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bottle_deposit_storage.rb
module BottleDeposit
  class Storage < ApplicationRecord
    self.table_name = 'bottle_deposit_storages'
  end
end

app/models/container.rb
# frozen_string_literal: true

class Container < ApplicationRecord
  has_many :pills
  belongs_to :user

  validates :name, :weight, presence: true
  validates :weight, numericality: true
end

app/models/pile.rb
# frozen_string_literal: true

class Pile < ApplicationRecord
  belongs_to :container, optional: true
  belongs_to :user

  enum kind: %i[bio paper plastic waste]
  validates :produced_at, :weight, :kind, presence: true
  validates :weight, numericality: true

  before_save :calculate_real_weight

  def calculate_real_weight
    self.real_weight = container.present? ? weight - container.weight : weight
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :people_in_household, numericality: { only_integer: true, greater_than: 0, less_than: 15 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit


  before_action :configure_permitted_parameters, if: :devise_controller?


  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:people_in_household])
  end

  private

  def authorize_user_pundit_rights(record)
    authorize record
  end

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore

    flash[:alert] = t("#{policy_name}.#{exception.query}",
                      scope: 'pundit',
                      default: :default)
    redirect_to root_path
  end

end

app/controllers/containers_controller.rb
# frozen_string_literal: true

class ContainersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_container, only: %w[edit update destroy]
  before_action only: %w[edit update destroy] do
    authorize_user_pundit_rights(@container)
  end

  def index
    @containers = Container.where(user_id: current_user.id)
  end

  def new
    @container = Container.new
  end

  def create
    @container = Container.new(container_params)

    if @container.save
      redirect_to containers_path, notice: t('.success')
    else
      flash[:alert] = @container.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    if @container.update(container_params)
      redirect_to containers_path, notice: t('.success')
    else
      flash[:alert] = @container.errors.full_messages
      render :edit
    end
  end

  def destroy
    @container.delete
    redirect_to containers_path
  end

  private

  def find_container
    @container = Container.find(params[:id])
  end

  def container_params
    container_params = params
                       .require(:container)
                       .permit(:name, :weight)
    container_params[:user_id] = current_user.id
    container_params
  end
end

app/controllers/graphs_controller.rb
# frozen_string_literal: true

class GraphsController < ApplicationController
  before_action :authenticate_user!

  def index
    @date = Date.today
    @graph_presenter = GraphPresenter.new(current_user.id)
  end
end

app/controllers/piles_controller.rb
# frozen_string_literal: true

class PilesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_pile, only: %w[edit update destroy]
  before_action only: %w[edit update destroy] do
    authorize_user_pundit_rights(@pile)
  end

  def index
    @piles = Pile.includes(:container)
                 .where(user_id: current_user.id)
                 .order('produced_at DESC')
  end

  def new
    @pile = Pile.new(produced_at: Time.now.strftime('%Y-%m-%d'))
  end

  def create
    @pile = Pile.new(pile_params)

    if @pile.save
      redirect_to piles_path, notice: t('.success')
    else
      flash[:alert] = @pile.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    if @pile.update(pile_params)
      redirect_to piles_path, notice: t('.success')
    else
      flash[:alert] = @pile.errors.full_messages
      render :edit
    end
  end

  def destroy
    @pile.delete
    redirect_to piles_path
  end

  private

  def find_pile
    @pile = Pile.find(params[:id])
  end

  def pile_params
    pile_params = params.require(:pile)
                        .permit(:weight,
                                :kind,
                                :container_id,
                                :produced_at)
    pile_params[:user_id] = current_user.id
    pile_params
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  FLASH_LEVEL = {
    'notice' => 'alert-info',
    'alert' => 'alert-danger'
  }.freeze

  def flash_class(level)
    "alert #{FLASH_LEVEL[level]}"
  end

  def kind_sign(waste_kind)
    "#{waste_kind}-sign rounded text-center"
  end
end

app/views/bottle_deposit_configurations/_form.html.haml
.card
  .card-header
    = "#{action} Bottle Deposit Configuration"
  = form_with model: bottle_deposit_configuration do |form|
    .card-body
      .form-group
        = form.label :name
        = form.text_field :name, class: 'form-control'
      .field
        = form.label :price
        = form.number_field :price, class: 'form-control'
    .card-footer
      = form.submit "#{action}", class: 'btn btn-success'
      = link_to 'Cancel', bottle_deposit_configurations_path, class: 'btn btn-danger pull-right'

app/views/containers/_form.haml
.card
  %h2.card-header
    = "#{action} Container"
  = form_with model: container do |form|
    .card-body
      .form-group
        = form.label :name
        = form.text_field :name, class: 'form-control'
      .field
        = form.label :weight
        = form.number_field :weight, class: 'form-control'
    .card-footer
      = form.button fa_icon('save', text: "#{action}"), class: 'btn btn-success'
      = link_to 'Cancel', containers_path, class: 'btn btn-outline-danger pull-right'

app/views/containers/edit.haml
= render partial: 'form', locals: { container: @container, action: 'Update' }

app/views/containers/index.haml
.card
  .card-header
    = link_to fa_icon('plus', text: 'New Container'), new_container_path, class: 'btn btn-success'
  %table.table
    %thead
      %tr
        %th Name
        %th.text-right Weight (in g)
        %th
    %tbody
      - @containers.each do |container|
        %tr
          %td.align-middle
            = container.name
          %td.text-right.align-middle
            = number_with_delimiter(container.weight, delimiter: ".")
          %td.text-right
            = link_to fa_icon("edit", text: 'Edit'), edit_container_path(container), class: 'btn btn-light'
            = link_to fa_icon("trash", text: 'Delete'), container_path(container), method: :delete, class: 'btn btn-danger'

app/views/containers/new.haml
= render partial: 'form', locals: { container: @container, action: 'Create' }

app/views/garbage/containers/_form.haml
.card
  .card-header
    = "#{action} Garbage Container"
  = form_with model: container do |form|
    .card-body
      .form-group
        = form.label :name
        = form.text_field :name, class: 'form-control'
      .field
        = form.label :weight
        = form.number_field :weight, class: 'form-control'
    .card-footer
      = form.submit "#{action}", class: 'btn btn-success'
      = link_to 'Cancel', garbage_containers_path, class: 'btn btn-outline-danger pull-right'

app/views/garbage/piles/_form.haml
.card
  .card-header
    = "#{action} Pile"
  = form_with model: pile do |form|
    .card-body
      .form-group
        = form.label :kind
        = form.select :kind, Garbage::Pile.kinds.keys, { selected: pile.kind }, class: 'form-control'
      .form-group
        = form.label :weight
        = form.number_field :weight, class: 'form-control'
      .form-group
        = form.label :produced_at
        = form.date_field :produced_at, class: 'form-control'
      .form-group
        = form.label :container_id
        = form.collection_select :container_id,
          Garbage::Container.all, :id, :name,
          { selected: pile.container_id },
          { class: 'form-control' }

    .card-footer
      = form.submit "#{action}", class: 'btn btn-success'
      = link_to 'Cancel', garbage_piles_path, class: 'btn btn-outline-danger pull-right'

app/views/garbage/piles/index.haml
.card
  .card-header
    = link_to fa_icon('plus', text: 'New Pile'), new_garbage_pile_path, class: 'btn btn-success'
  %table.table
    %thead
      %tr
        %th{:scope => "col"} Kind
        %th{:scope => "col"} Weight
        %th{:scope => "col"} Real Weight
        %th{:scope => "col"} Produced At
        %th{:scope => "col"} 
    %tbody
      - @piles.each do |pile|
        %tr
          %td{:scope => "row"}= pile.kind
          %td{:scope => "row"}= pile.weight
          %td{:scope => "row"}= pile.real_weight
          %td{:scope => "row"}= pile.produced_at
          %td.text-right
            = link_to fa_icon("edit", text: 'Edit'), edit_garbage_pile_path(pile), class: 'btn btn-default'
            = link_to fa_icon("trash", text: 'Delete'), garbage_pile_path(pile), method: :delete, class: 'btn btn-danger'

app/views/graphs/index.haml
.alert.alert-warning
  The graphs are still
  %span.beta-sign.rounded
    beta
  %span
    and needs to be imporved this is only a first overview.
.card
  .card-body
    = high_chart_globals(@graph_presenter.chart_globals)
    = high_chart('waste-graph', @graph_presenter.chart)

.card
  .card-header
    %h3= "Monthly Statistics: #{@date.strftime("%B %Y")}"
  .card-body
    %table.table
      %thead
        %tr
          %th.text-left Kind
          %th.text-left Your household (total)
          %th.text-left Your household (per person)
          %th.text-right Average household (per person)
          %th Source
      %tbody
        - GraphPresenter::GARBAGE.each do |key, value|
          - household_weight = Pile.where(user_id: current_user.id).where(kind: key).group("DATE_TRUNC('month', produced_at)").sum(:weight).values.first
          %tr
            %td.text-left= key
            %td.text-left="#{household_weight}g"
            %td.text-left="#{household_weight/current_user.people_in_household}g"
            %td.text-right= "#{value[:limit]} g"
            %td= link_to 'Source', value[:source]

app/views/layouts/_external_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container
    = link_to root_path, class: 'navbar-brand' do
      = image_tag('logo.png')
      Garbage-Tracker
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse.pull-ight
      .navbar-nav.ml-auto
        .nav-item
          = link_to 'Login', new_user_session_path, class: 'nav-link'

app/views/layouts/_internal_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container
    = link_to piles_path, class: 'navbar-brand' do
      = image_tag('logo.png')
      Garbage-Tracker
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse.pull-ight
      %ul.navbar-nav.ml-auto
        %li.nav-item
          = link_to graphs_path, class: 'nav-link' do
            Graphs
            %span.rounded.text-center.beta-sign
              beta
        %li.nav-item
          = link_to 'Piles', piles_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Container', containers_path, class: 'nav-link'
        %li.nav-item.dropdown
          %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            %strong= current_user.email
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to 'Edit User', edit_user_registration_path, class: 'dropdown-item'
            .dropdown-divider
            = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Garbage-Tracker
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.d-flex.flex-column
    - if user_signed_in?
      = render partial: 'layouts/internal_navbar'
    - else
      = render partial: 'layouts/external_navbar'
    .container.main-body
      - flash.each do |key, value|
        %div{class: flash_class(key)}
          = value

      = yield

app/views/piles/_form.haml
.card
  %h2.card-header
    = "#{action} Pile"
  = form_with model: pile do |form|
    .card-body
      .form-group
        = form.label :kind
        = form.select :kind, Pile.kinds.keys, { selected: pile.kind }, class: 'form-control'
      .form-group
        = form.label :weight
        = form.number_field :weight, class: 'form-control'
      .form-group
        = form.label :produced_at
        = form.date_field :produced_at, class: 'form-control'
      .form-group
        = form.label :container_id
        = form.collection_select :container_id,
          Container.where(user_id: current_user.id), :id, :name,
          { selected: pile.container_id,
            include_blank: 'No Container' },
          { class: 'form-control' }

    .card-footer
      = form.button fa_icon('save', text: "#{action}"), type: 'submit', class: 'btn btn-success'
      = link_to 'Cancel', piles_path, class: 'btn btn-outline-danger pull-right'

app/views/piles/edit.haml
= render partial: 'form', locals: { pile: @pile, action: 'Update' }

app/views/piles/index.haml
.card
  .card-header
    = link_to fa_icon('plus', text: 'New Pile'), new_pile_path, class: 'btn btn-success'
  %table.table
    %thead
      %tr
        %th Produced At
        %th.text-center Kind
        %th.text-right Tracked Weight (in g)
        %th Container
        %th
    %tbody
      - @piles.each do |pile|
        %tr
          %td.align-middle
            = pile.produced_at
          %td.align-middle
            %div{ class: kind_sign(pile.kind) }
              = pile.kind
          %td.text-right.align-middle
            = number_with_delimiter(pile.real_weight, delimiter: '.')
          %td
            - if pile.container
              = link_to fa_stacked_icon("recycle", text: pile.container.name), edit_container_path(pile.container), class: 'btn btn-light'
          %td.text-right
            = link_to fa_icon("edit", text: 'Edit'), edit_pile_path(pile), class: 'btn btn-light'
            = link_to fa_icon("trash", text: 'Delete'), pile_path(pile), method: :delete, class: 'btn btn-danger'

app/views/piles/new.haml
= render partial: 'form', locals: { pile: @pile, action: 'Create' }